x = input("ilk sayi giriniz. ")
y = input("ikinci sayi giriniz. ")
print (int(x)+int(y))
print (int(x)-int(y))
print (int(x)*int(y))
print (int(x)/int(y))
print (int(x)//int(y))
print (int(x)%int(y))
print (int(x)**int(y))
